from board import ReversiBoard
import random
import time

BLACK = 'x' # player black
WHITE = 'o' # player white
EMPTY = '.'

#######################
'''
TODO:
1. ADD welcome and guide message in the very beginning
2. change UI, remove board or '.'
3. board.showboard also shows both scores
4. if a move is generated by computer, show move position
5. !!!provide pass option if no legal moves
6. !!!Documentation

'''
#######################

class Cell:
    chars ='bw' 
alphabet = 'abcdefghijklmnopqrstuvwxyz'

def showLegalMove(board, player1):
    move = board.getAllLegalMoves(player1)
    print(move)
    if len(move) == 0:
        print("You have no legal move!")
        return True
    else:
        print("Here are all the legal moves:")
        coord = []
        for i in move:
            position = board.point2position(i)
            letter = alphabet[position[0]]
            coord.append(letter+str(position[1]+1))      
        print(coord) 

def getUserColor():
    print("x is black color stone, o is white color stone")
    while True:
        choose = input("Please specify the color of stone you want to use(x/o): ")
        if choose.lower() in ["o", "w", "white"]:
            return WHITE, BLACK
        elif choose.lower() in ["x", "b", "black"]:
            return BLACK, WHITE
        print("invalid input, please input again")
    
def showResult(board):
    winner = board.getWinner()
    if winner == "tie":
        "The game ties"
    else:
        print("The winner is:", winner, "with score of", board.getMark(winner))
    
def main():
  
    board = ReversiBoard(8)
    score = {BLACK:2, WHITE:2}
    player1, player2 = getUserColor()

    board.printMenu() 
    while True:
        if board.isEnd():
            showResult(board)
            #winner = board.getWinner() 
            #if winner == player1:
                #print("The winner is:", winner)
                #score["Player1"] = board.getMark(player1)
            #elif winner == player2:
                #print("The winner is:", winner)
                #score["Player2"] = board.getMark(player2)
            #else:
                #print("tie")
            return 
        else:
            board.showBoard()
            #show legal moves
            showLegalMove(board, player1)

            #get user input
            cmd = input('')
            if len(cmd)==0:         
                print('\n ... adios :)\n')              
                return              
            if cmd[0][0]=='h':                        
                board.printMenu()               
            elif cmd[0][0] in Cell.chars:                                 
                check = board.makeMove(cmd)  
                # if the player make a valid move, player2 will play automatically  
                if check: 
                    moves = board.getAllLegalMoves(player2)
                    board.play(player2, random.choice(moves))
                    #point = greedy(board, player2)
                   # board.play(player2, point)          


if __name__ == '__main__':
    main()